### ISSUE TITLE
0002.forked

### ISSUE THREAD

**Issue by rickvschmidt** [austinginder/recipe-card#2]
Since upgrading to 0002.forked from 0001.forked the cards won't render at all on any of my clients blogs. Downgraded to 0001.forked.

**Comment by austinginder** [comment]
Yes the plugin had some nasty JS methods which would remove the whole recipe card if the "Save Recipe" button was hidden. In the new update I remove that however I suspect your experiencing some browser caching. I'll bump version numbers to prevent browser caching.

**Comment by rickvschmidt** [comment]
Wow... they really had a lot of nasty code in this. Are you looking to maintain this going forward? The domain of the company is down and they haven't updated the plugin in 3 years, which doesn't look like a good sign.

**Comment by austinginder** [comment]
Agreed it doesn't look like a good sign.

I run a [WordPress hosting and maintenance service](https://anchor.host) for small businesses. I forked the plugin as it was the quickest way to resolve issues with this plugin and one of my customer's website. I have no interested in adding new features or making improvements. I would see this fork as workaround to allow people some time to find and switch to something new.

**Comment by austinginder** [comment]
Try the released version: https://github.com/austinginder/recipe-card/releases. It should remove the save button and hopefully not remove the recipe cards :).
