### ISSUE TITLE
Not rendering recipe-card creation page

### ISSUE THREAD

**Issue by tudoquebonito** [austinginder/recipe-card#3]
![screen shot 2017-02-27 at 16 59 17 2](https://cloud.githubusercontent.com/assets/26067532/23370901/1d28da00-fd0e-11e6-87c0-181582378de1.png)
I've changed all my Recipe-Card files by the ones you have on the release link you gave in the other issue, but when i click the Recipe-Card on the Tiny-MCE the pages doesn't seem to render correctly. I can only see the labels, but not the input fields or any of the images. What am i doing wrong?

**Comment by tudoquebonito** [comment]
THe problem is now solved. I guess my browser was not updating or add previous files on cache. Everything seems to be working fine now. Thanks!

**Comment by austinginder** [comment]
There very well might be other bugs. If you happen to find steps to reproduce, feel free to create a new issue. While I can't promise I'll fix, I'm happy to facilitate the conversation.
