### ISSUE TITLE
Nutritional Info not working when I save

### ISSUE THREAD

**Issue by jessyhanley** [austinginder/recipe-card#6]
Hello,

Thanks so much for the fork of the yum print plugin.  I have noticed that now whenever I add a new recipe or update an existing one all of my nutritional info zero's out.  At first, I thought I broke it with some of my edits for the display, but the same thing happened when I restored the original file from the GitHub Install.   Any idea why that would be happening?

Here is an example:

- New recipe: [Cioppino Seafood Stew](https://www.jessyandmelissa.com/recipe/recipes-by-cuisine/italian/cioppino-seafood-stew) - All 0'd out for nutritional info.
- Old Recipe: [Chicken Marsala](https://www.jessyandmelissa.com/recipe/recipes-by-course/main-courses/poultry/chicken-marsala-weight-watchers) - Seems like VERY high cal counts etc., but I suspect it's not dividing the values by # of servings. 

Thank You In advance,
Jessy

**Comment by austinginder** [comment]
@jessyhanley This forked plugin isn't being supported. I made it out of necessity for one of my customers during a yumprint.com server outage which causes all recipe cards to disappear. It was sufficient enough for them to access their recipes and move them over to another system.

I recommend using the [official plugin](https://yumprint.com/recipecard) and contacting their support email address if you run into any issues with their plugin. If you don't receive any help from official channels then I'd recommend finding an alternative, more updated recipe plugin.
